# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackaThon2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackaThon2

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-voice', :path => '../node_modules/react-native-voice'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
